const Router = require('express')
const router = new Router()
const itemRouter = require('./itemRouter')
const headerRouter = require('./headerRouter')
const mediaRouter = require('./media/mediaRouter')
const promoRouter = require('./promoRouter')
const advantageRouter = require('./pages/advantageRouter')
const formOrderRouter = require('./main/formOrderRouter')
const videoRouter = require('./media/videoRouter')
const footerRouter = require('./main/footerRouter')
const aboutRouter = require('./pages/aboutRouter')
const reasonRouter = require('./main/reasonRouter')
const massMediaRouter = require('./massMediaRouter')
const productionInfoRouter = require('./productionInfoRouter')
const feedbackRouter = require('./feedbackRouter')
const techRouter = require('./techRouter')
const loginRouter = require('./auth/loginRouter')
const mailRouter = require('./mailing/mailRouter')
const deliveryRouter = require('./deliveryRouter')

router.use('/item', itemRouter)
router.use('/header', headerRouter)
router.use('/media', mediaRouter)
router.use('/promo', promoRouter)
router.use('/advantages', advantageRouter)
router.use('/forms', formOrderRouter)
router.use('/video', videoRouter)
router.use('/footer', footerRouter)
router.use('/about', aboutRouter)
router.use('/reasons', reasonRouter)
router.use('/massmedia', massMediaRouter)
router.use('/prodinfo', productionInfoRouter)
router.use('/feedback', feedbackRouter)
router.use('/tech', techRouter)
router.use('/login', loginRouter)
router.use('/mail', mailRouter)
router.use('/delivery', deliveryRouter)

module.exports = router
