const Router = require('express')
const router = new Router()
const itemRouter = require('./itemRouter')
const headerRouter = require('./headerRouter')
const mediaRouter = require('./mediaRouter')
const promoRouter = require('./promoRouter')
const advantageRouter = require('./advantageRouter')
const formOrderRouter = require('./formOrderRouter')
const videoRouter = require('./videoRouter')
const footerRouter = require('./footerRouter')
const aboutRouter = require('./aboutRouter')
const reasonRouter = require('./reasonRouter')
const massMediaRouter = require('./massMediaRouter')
const productionInfoRouter = require('./productionInfoRouter')
const feedbackRouter = require('./feedbackRouter')
const techRouter = require('./techRouter')

router.use('/item', itemRouter)
router.use('/header', headerRouter)
router.use('/media', mediaRouter)
router.use('/promo', promoRouter)
router.use('/advantages', advantageRouter)
router.use('/forms', formOrderRouter)
router.use('/video', videoRouter)
router.use('/footer', footerRouter)
router.use('/about', aboutRouter)
router.use('/reasons', reasonRouter)
router.use('/massmedia', massMediaRouter)
router.use('/prodinfo', productionInfoRouter)
router.use('/feedback', feedbackRouter)
router.use('/tech', techRouter)

module.exports = router
