name: CI
on:
  push:
    branches:
      - main
jobs:
  build_pub_run_on_server:
    runs-on: [ubuntu-latest]
    env:
      TOKEN: ${{ secrets.DOCKER_TOKEN }}
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      IMAGE: ${{ secrets.DOCKER_IMAGE }}
      SSH_USER: ${{secrets.SSH_USER}}
      SSH_HOST: ${{secrets.SSH_HOST}}
      #      SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      SSH_KEY_PATH: ~/.ssh/id_rsa
    steps:
      - name: Login to docker
        run: echo $TOKEN | docker login -u $LOGIN --password-stdin
      - uses: actions/checkout@main
      - name: Build & push image
        run: docker buildx build --push --build-arg LOGIN=$LOGIN -t $LOGIN/$IMAGE:1.0 -t $LOGIN/$IMAGE:latest .
      - name: Work on server
        run: |
          mkdir -p ~/.ssh/
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "docker compose rm -s -f backend"
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "docker rmi $LOGIN/$IMAGE"
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "docker compose up -d backend"
          ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST "docker compose restart"