name: CI
on:
  push:
    branches:
      - main
jobs:
  build_and_pub:
    runs-on: [ubuntu-latest]
    env:
      TOKEN: ${{ secrets.DOCKER_TOKEN }}
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      IMAGE: ${{ secrets.DOCKER_IMAGE }}
    steps:
      - name: Login to docker
        run: echo $TOKEN | docker login -u $LOGIN --password-stdin
      - uses: actions/checkout@master
      - name: Build & push image
        run: docker buildx build --push --build-arg LOGIN=$LOGIN -t $LOGIN/$IMAGE:1.0 -t $LOGIN/$IMAGE:latest .